django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
]

store/urls.py
from django.urls import path
from store.views import index, about, products_json, products, product_detail

app_name = 'store'

urlpatterns = [
    path('', index, name='home'),
    path('about/',about, name='about'),
    path('products.json/', products_json, name='products_json'),
    path('products/', products, name='products'),
    path('products/<int:product_pk>/',product_detail, name = 'product_detail'),

]

store/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'categories'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    description = models.TextField(null=True, blank=True)
    is_available = models.BooleanField(default=True)
    on_sale = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        db_table = 'product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

university/models.py
from django.db import models





class Teachers(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    email = models.EmailField()

    class Meta:
        db_table = 'teachers'

class Course(models.Model):
    name = models.CharField(max_length=30)
    teacher = models.ForeignKey(Teachers, on_delete=models.CASCADE)
    credit = models.IntegerField()

    class Meta:
        db_table = 'courses'


class Students(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    dob = models.DateField()
    course = models.ManyToManyField(Course)

    class Meta:
        db_table = 'students'

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse

from store.models import Product, Category


# def index(request):
#     return HttpResponse("<h1>Hello, world. You're at the store index.</h1>")
#
# def about(request):
#     return HttpResponse("<h1>This is about page</h1>")

def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def products_json(request):
    all_products = Product.objects.all()
    return JsonResponse({'products': list(all_products.values())})

def products(request):
    all_product = Product.objects.all()
    return render(request, 'products.html', {'products': all_product})

def product_detail(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    return render(request, 'product_detail.html', {'product': product})

university/views.py
from django.shortcuts import render

# Create your views here.

store/templates/about.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>
    <h1>This is about page</h1>
    <a href="{% url 'store:home' %}">Home Page</a>


</body>
</html>

store/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home page</title>
</head>
<body>
    <h1>This is home page</h1>

    <a href="{% url 'store:products' %}">Here are all products page</a>
    <hr>
    <a href="{% url 'store:about' %}">About page</a>



</body>
</html>

store/templates/product_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{product}} Details</title>
</head>
<body>
    Title: {{ product.title }}
    <br>
    Price: {{ product.price }}
    <br>
    Description: {{ product.Description }}
    <br>
    Quantity: {{ product.Quantity }}
    <br>
    Stock: {{ product.is_available }}
    <br>

</body>
</html>

store/templates/products.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Products</title>
</head>
<body>
<h1>This is products page</h1>
<a href="{% url 'store:home' %}">Home page</a>
    <ul>
    {% for product in products %}
        <a href="{% url 'store:product_detail' product_pk=product.pk %}"><li>Title: {{ product.title }} -- {{ product.price }} Gel </li></a>
    {% endfor %}
    </ul>

</body>
</html>